packages:
  - "apps/*"
  - "packages/*"
  - "packages/config/*"
  - "packages/core/*"
  - "packages/core/kit/*" 
  - "packages/core/xr/*"
  - "packages/core/ecs/*"
  - "packages/core/run/*"
  - "packages/utilities/*"
  - "packages/utilities/util/*"
  - "packages/utilities/hooks/*"
  - "packages/utilities/duck/*"
  - "packages/utilities/props/*"
  - "packages/utilities/raymarcher/*"
