# Cargo.toml
[package]
name = "inspatial-dao"
version = "0.1.0"
edition = "2025"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
anchor-lang = { version = "0.28.0", features = ["wasm"] }
anchor-spl = { version = "0.28.0", features = ["wasm"] }
getrandom = { version = "0.2", features = ["js"] }
console_error_panic_hook = "0.1"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "console",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.5"

[build-dependencies]
wasm-pack = "0.12"